### ISSUE TITLE
Implement sharding

### ISSUE THREAD

**Issue by MattIPv4** [MattIPv4/1.1.1.1-Discord#13]
As the bot begins to grow, there will be a point where it needs to support sharding.

It'd be great if it was still a single executable to be run, that handled spawning all the required shards.

**Comment by andersfylling** [comment]
Disgord handles sharding behind the scenes. So if Discord suddenly disconnect your bot, due to too few shards, Disgord will upscale the number of shards and reconnect. Hope this helps!

**Comment by MattIPv4** [comment]
Oh, cool, awesome! I'll close this out then, TIL.
