### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: discordCommands is not iterable

### ISSUE THREAD

**Issue by ClaraCrazy** [MattIPv4/1.1.1.1-Discord#28]
Hey.

tried installing the bot myself and failed when doing npm run dev.

here is the full error log: 

(node:47656) UnhandledPromiseRejectionWarning: TypeError: discordCommands is not iterable
    at module.exports.registerCommands (C:\Users\CENSORED\Desktop\DNS-over-Discord-2\src\build\commands.js:77:27)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async module.exports (C:\Users\CENSORED\Desktop\DNS-over-Discord-2\src\build\index.js:20:29)
(Use `node.EXE --trace-warnings ...` to show where the warning was created)
(node:47656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:47656) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
thread 'main' panicked at 'could not parse wranglerjs output: Error("EOF while parsing a value", line: 1, column: 0)', src\wranglerjs\mod.rs:49:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Note: This command was run via npm module 'win-node-env'
npm ERR! code ELIFECYCLE
npm ERR! errno 3221226505
npm ERR! dns-over-discord@1.0.0 dev: `NODE_ENV=development wrangler dev`
npm ERR! Exit status 3221226505
npm ERR!
npm ERR! Failed at the dns-over-discord@1.0.0 dev script.

**Comment by MattIPv4** [comment]
I suggest logging what `discordCommands` is after this line to see what's going on:
https://github.com/MattIPv4/DNS-over-Discord/blob/1063b45bf3f61f4bc44bba5cfdeade3ae2f9e88d/src/build/commands.js#L74

Are you sure all the environment variables are set as required? (Windows can be funky with env vars, I suggest using WSL if you can)

**Comment by ClaraCrazy** [comment]
"Are you sure all the environment variables are set as required?" Yup. also tried with and without a space after the equal sign and with & without "" just to be sure

"Suggest using WSL" 
yeah will give it a try later


nvm what I said before I edited the comment. must have missplaced my brain there for a second

**Comment by MattIPv4** [comment]
No further progress, closing.
