### ISSUE TITLE
Inviting bot not joining server

### ISSUE THREAD

**Issue by cenourinha** [MattIPv4/1.1.1.1-Discord#31]
Hi! I've tried to invite the bot several times but it doesn't show up on the server.
Is the bot still working?

**Comment by MattIPv4** [comment]
👋 Once you've invited the bot, the commands should be available in the message box of each channel -- type `/` to access them. The bot won't show up in the members' list as it is not a member of the server, you're just inviting the application to make the commands available.

**Comment by cenourinha** [comment]
It wasn't working for the first minutes, but now i'm able to use the commands. Thanks!

**Comment by MattIPv4** [comment]
Sounds like this is resolved, closing.
