### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by omsenjalia** [MattIPv4/1.1.1.1-Discord#34]
![Screenshot_20210528-233033_Brave](https://user-images.githubusercontent.com/69719569/120024837-6534d080-c00d-11eb-8624-9fe949a4cdda.jpg)

**Comment by MattIPv4** [comment]
Hi there! This project is designed to be run in the Cloudflare workers environment, not in a Node.js environment. Please make sure you have the dependencies installed that are needed to build and deploy the worker, and that you're actually deploying it to a Cloudflare workers environment.

You can re-open this issue, or create a new one, if you continue to encounter errors once you've installed the dependencies and are running the project in Cloudflare workers.

**Comment by omsenjalia** [comment]
I have installed all the dependencies

**Comment by omsenjalia** [comment]
Same error

**Comment by MattIPv4** [comment]
Your screenshot shows you trying to run this in a Node.js environment -- that will not work. You need to follow the deployment instructions and deploy this in a Cloudflare Workers environment. If you continue to encounter errors once you are using the project in the intended environment, let me know and I'll take a closer look.

**Comment by omsenjalia** [comment]
Sure, Sure, I'll try

**Comment by omsenjalia** [comment]
![Screenshot_20210528-234903_Brave](https://user-images.githubusercontent.com/69719569/120026221-6535d000-c00f-11eb-98d7-e6f9d32e3d8b.jpg)

**Comment by MattIPv4** [comment]
I recommend making sure you're familiar with Cloudflare Workers generally before working with this project, you can learn more at https://developers.cloudflare.com/workers/get-started/guide

Please make sure you've also actually followed the steps in the readme for deploying the worker if you wish to run it yourself on Cloudflare Workers.
