### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by omsenjalia** [MattIPv4/1.1.1.1-Discord#35]
Hey, I just signed up for cloudflare thing that you told me to do, NPM is not available and nodejs is not available too, can I have a tutorial on the setting the bot up?

**Comment by omsenjalia** [comment]
https://github.com/MattIPv4/DNS-over-Discord#development

Followed this too

**Comment by MattIPv4** [comment]
As I mentioned in https://github.com/MattIPv4/DNS-over-Discord/issues/34#issuecomment-850591792 I recommend looking at the docs that are available to familiarise yourself with the Cloudflare Workers environment first. I am happy to provide technical support via issues for actual issues with the bot, but I am less willing to act as a tutor for using a runtime environment -- that is beyond the scope of support I'm willing to provide.

https://github.com/MattIPv4/DNS-over-Discord#development has all the key steps needed to get the bot running in a Cloudflare Workers runtime for local development, and https://github.com/MattIPv4/DNS-over-Discord#deployments has information on how to deploy it to Cloudflare Workers in a production context for general usage.
