### ISSUE TITLE
Deploy via GitHub Actions

### ISSUE THREAD

**Issue by MattIPv4** [MattIPv4/1.1.1.1-Discord#43]
Create a GitHub Actions workflow the runs on pushes to a branch named `production`. This workflow should deploy the production environment of the worker to Cloudflare.

As a follow-up, once this initial workflow has been created, duplicate it for a branch named `staging`, and have it deploy the staging environment of the worker to Cloudflare.

**Comment by mohan-13** [comment]
Hello ! I would like to pick up this ? Could you please assign me to this? Thanks

**Comment by MattIPv4** [comment]
Sure thing

**Comment by MattIPv4** [comment]
For reference, I imagine you'll want to utilise https://github.com/marketplace/actions/deploy-to-cloudflare-workers-with-wrangler

**Comment by mohan-13** [comment]
Yup! Thanks. I will get started and we shall discuss if I need something here.

**Comment by mohan-13** [comment]
I am new to Wrangler. Can you please confirm whether I need to create respective .env file before deployment ? If needed then I can pick it up from Github Secrets right ?

**Comment by MattIPv4** [comment]
Yes, the .env file will need to be created. And yeah, building it from GitHub Secrets seems like the best approach

**Comment by MattIPv4** [comment]
Alternatively, you could change the Webpack script to inject the full env, and then just use the environment directly without the .env file: https://github.com/MattIPv4/DNS-over-Discord/blob/6c457254930c705b347fa8ab69589b7fb7bfcd0d/webpack.config.js#L15
