### ISSUE TITLE
Allow setting the cd flag

### ISSUE THREAD

**Issue by MattIPv4** [MattIPv4/1.1.1.1-Discord#64]
Similar to how one can currently set the `+short` flag for requests, allow the user to set the `+cdflag` option to disable DNSSEC checking.

This should be exposed as an optional option on both the `dig` and `multi-dig` commands. It should map to `+cdflag` in dig command that is rendered/parsed, similar to how short maps to `+short`.

README documentation should be updated to explain using the checking disabled option and what it does.

When checking is disabled for a query, a warning should be appended to the embed, indicating that checking was disabled for the query. `:warning: cd bit set for request, DNSSEC validation disabled.`.

**Comment by naomi-lgbt** [comment]
Drive by comment to say I'd be interested in poking at this but I've got a very full plate so if someone else beats me to it that's poggers

**Comment by Dhravya** [comment]
Hi there! You can assign it to me :)

**Comment by Dhravya** [comment]
Done in #65 (you can close this issue now)
