### ISSUE TITLE
is the bot no longer usable?, because I can't invite it on my server?

### ISSUE THREAD

**Issue by krisdewa** [MattIPv4/1.1.1.1-Discord#69]

**Comment by MattIPv4** [comment]
👋 I'm not sure what you're asking here. The screenshot you're showing indicates that you did successfully invite the bot?

**Comment by krisdewa** [comment]
I managed to invite the bot but I invite it on my server the bot doesn't appear.

**Comment by MattIPv4** [comment]
When you say the bot doesn't appear, are the commands showing when you try using `/dig`? The bot is an application, not a bot user, so it doesn't have a presence.

**Comment by krisdewa** [comment]
it turns out that my discord crashed, thank you sir
