### ISSUE TITLE
User-Installable App

### ISSUE THREAD

**Issue by oddyamill** [MattIPv4/1.1.1.1-Discord#83]
I suggest enabling the "User Install" authorization method for the bot (at Discord Developer Portal)

![image](https://github.com/MattIPv4/DNS-over-Discord/assets/43600905/74902fbf-f645-4c28-8ae0-397f6dfec189)

**Comment by MattIPv4** [comment]
I have enabled the setting for the app, though it will not be usable in DMs until I get the work described in https://github.com/MattIPv4/workers-discord/issues/10 added (which is blocked by https://github.com/discordjs/discord-api-types/pull/921)

**Comment by wdhdev** [comment]
@MattIPv4 Hey Matt, is this now possible since that PR has been merged or am I missing something here?
